name: Ubuntu-Tailscale-3xUI

on:
  workflow_dispatch:

jobs:
  panel:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Update packages
        run: sudo apt update && sudo apt install -y curl wget git jq sqlite3

      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTH_KEY }}" --hostname="gh-${{ github.run_id }}" --advertise-exit-node

      - name: Install 3x-ui
        run: echo "y" | curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh | sudo bash

      - name: Wait and Start x-ui
        run: |
          sleep 10
          sudo systemctl restart x-ui
          sleep 10

      - name: Enable SSH
        run: |
          echo "root:123456" | sudo chpasswd
          sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Show Info
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          PORT=$(sudo sqlite3 /etc/x-ui/x-ui.db "select value from settings where key='webPort';")
          WEBPATH=$(sudo sqlite3 /etc/x-ui/x-ui.db "select value from settings where key='webBasePath';")
          USER=$(sudo sqlite3 /etc/x-ui/x-ui.db "select value from settings where key='webAdminUsername';")
          PASS=$(sudo sqlite3 /etc/x-ui/x-ui.db "select value from settings where key='webAdminPassword';")
          echo "=============================="
          echo "TAILSCALE IP : $TAILSCALE_IP"
          echo "PANEL URL    : http://$TAILSCALE_IP:$PORT/$WEBPATH"
          echo "USER         : $USER"
          echo "PASS         : $PASS"
          echo "SSH          : ssh root@$TAILSCALE_IP"
          echo "SSH PASS     : 123456"
          echo "=============================="

      - name: Keep Alive
        run: |
          while true; do
            sleep 300
          done
