name: Ubuntu-Tailscale-3xUI

on: workflow_dispatch:

jobs:panel:runs-on: ubuntu-latest
timeout-minutes: 360

steps:
  - name: Update packages
    run: |
      sudo apt update
      sudo DEBIAN_FRONTEND=noninteractive apt install -y curl wget git openssh-server sudo

  - name: Install Tailscale
    run: |
      curl -fsSL https://tailscale.com/install.sh | sh

  - name: Connect Tailscale
    run: |
      sudo tailscale up \
        --authkey="${{ secrets.TAILSCALE_AUTH_KEY }}" \
        --hostname="gh-${{ github.run_id }}"

  - name: Enable SSH
    run: |
      sudo systemctl enable ssh
      sudo systemctl restart ssh

  - name: Enable Root Login
    run: |
      echo "root:123456" | sudo chpasswd

      sudo sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
      sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config

      sudo systemctl restart ssh

  - name: Install 3x-ui
    run: |
      curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh | sudo bash

  - name: Show Information
    run: |
      echo "===== Tailscale IP ====="
      tailscale ip -4

      echo ""
      echo "SSH:"
      echo "ssh root@$(tailscale ip -4)"

      echo ""
      echo "x-ui status:"
      sudo systemctl status x-ui --no-pager || true

  - name: Keep Alive
    run: |
      while true; do
        echo "running $(date)"
        sleep 300
      done
